services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fsd-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    environment:
      PORT: 3000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fsd-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
