sonar.projectKey=full-stack-web-dev
sonar.projectName=full stack web dev
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/pb_data/**,**/*.spec.ts,**/*.test.ts,**/*.d.ts
